packages:
  - packages/*
  - docs
  - skills

catalog:
  '@eslint/compat': ^1
  '@oclif/core': 4.8.0
  '@oclif/prettier-config': ^0.2.1
  '@oclif/test': ^4
  '@salesforce/dev-config': ^4.3.2
  '@types/chai': ^4
  '@types/mocha': ^10
  '@types/node': ^22
  '@types/sinon': ^21.0.0
  c8: ^11.0.0
  chai: ^4
  cliui: 9.0.1
  eslint: ^9
  eslint-config-oclif: ^6
  eslint-config-prettier: ^10
  eslint-plugin-header: ^3.1.1
  eslint-plugin-prettier: ^5.5.5
  glob: 13.0.0
  jsonschema: 1.5.0
  mocha: ^11
  msw: ^2.12.4
  oclif: ^4
  open: 11.0.0
  prettier: ^3.8.3
  shx: ^0.3.3
  sinon: ^21.0.1
  tsx: ^4
  typescript: ^5
  typescript-eslint: ^8

minimumReleaseAge: 2880

minimumReleaseAgeExclude: []

nodeLinker: hoisted

onlyBuiltDependencies:
  - unrs-resolver
  - yarn

overrides:
  '@isaacs/brace-expansion@<=5.0.0': '>=5.0.1'
  baseline-browser-mapping: '>=2.9.19'
  diff@>=4.0.0 <4.0.4: '>=4.0.4'
  diff@>=5.0.0 <5.2.2: '>=5.2.2'
  esbuild@<=0.24.2: '>=0.25.0'
  fast-xml-parser@>=4.3.6 <=5.3.3: '>=5.3.4'
  hono@<4.11.4: '>=4.11.4'
  hono@<4.11.7: '>=4.11.7'
  js-yaml@>=4.0.0 <4.1.1: '>=4.1.1'
  lodash@>=4.0.0 <=4.17.22: '>=4.17.23'
  mdast-util-to-hast@>=13.0.0 <13.2.1: '>=13.2.1'
  preact@>=10.27.0 <10.27.3: '>=10.27.3'
  picomatch@>=2.0.0 <3.0.0: 2.3.2
  picomatch@>=4.0.0 <4.0.4: 4.0.4
  qs@<6.14.2: '>=6.15.2'

savePrefix: ''

trustPolicy: no-downgrade

trustPolicyExclude: []
